/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as RentACampRouteImport } from './routes/rent-a-camp'
import { Route as RuralStayRouteImport } from './routes/rural-stay'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as DestinationsKoraputRouteImport } from './routes/destinations.koraput'
import { Route as DestinationsRamachandiRouteImport } from './routes/destinations.ramachandi'
import { Route as ToursKoraput2DayRouteImport } from './routes/tours.koraput-2-day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const RentACampRoute = RentACampRouteImport.update({
  id: '/rent-a-camp',
  path: '/rent-a-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralStayRoute = RuralStayRouteImport.update({
  id: '/rural-stay',
  path: '/rural-stay',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsKoraputRoute = DestinationsKoraputRouteImport.update({
  id: '/koraput',
  path: '/koraput',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsRamachandiRoute = DestinationsRamachandiRouteImport.update({
  id: '/ramachandi',
  path: '/ramachandi',
  getParentRoute: () => DestinationsRoute,
} as any)
const ToursKoraput2DayRoute = ToursKoraput2DayRouteImport.update({
  id: '/koraput-2-day',
  path: '/koraput-2-day',
  getParentRoute: () => ToursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/plan-trip': typeof PlanTripRoute
  '/rent-a-camp': typeof RentACampRoute
  '/rural-stay': typeof RuralStayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
  '/tours/koraput-2-day': typeof ToursKoraput2DayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/plan-trip': typeof PlanTripRoute
  '/rent-a-camp': typeof RentACampRoute
  '/rural-stay': typeof RuralStayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
  '/tours/koraput-2-day': typeof ToursKoraput2DayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/plan-trip': typeof PlanTripRoute
  '/rent-a-camp': typeof RentACampRoute
  '/rural-stay': typeof RuralStayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
  '/tours/koraput-2-day': typeof ToursKoraput2DayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/destinations'
    | '/faq'
    | '/plan-trip'
    | '/rent-a-camp'
    | '/rural-stay'
    | '/sitemap.xml'
    | '/tours'
    | '/destinations/koraput'
    | '/destinations/ramachandi'
    | '/tours/koraput-2-day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/destinations'
    | '/faq'
    | '/plan-trip'
    | '/rent-a-camp'
    | '/rural-stay'
    | '/sitemap.xml'
    | '/tours'
    | '/destinations/koraput'
    | '/destinations/ramachandi'
    | '/tours/koraput-2-day'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/destinations'
    | '/faq'
    | '/plan-trip'
    | '/rent-a-camp'
    | '/rural-stay'
    | '/sitemap.xml'
    | '/tours'
    | '/destinations/koraput'
    | '/destinations/ramachandi'
    | '/tours/koraput-2-day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  PlanTripRoute: typeof PlanTripRoute
  RentACampRoute: typeof RentACampRoute
  RuralStayRoute: typeof RuralStayRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursRoute: typeof ToursRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-a-camp': {
      id: '/rent-a-camp'
      path: '/rent-a-camp'
      fullPath: '/rent-a-camp'
      preLoaderRoute: typeof RentACampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural-stay': {
      id: '/rural-stay'
      path: '/rural-stay'
      fullPath: '/rural-stay'
      preLoaderRoute: typeof RuralStayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/koraput': {
      id: '/destinations/koraput'
      path: '/koraput'
      fullPath: '/destinations/koraput'
      preLoaderRoute: typeof DestinationsKoraputRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/ramachandi': {
      id: '/destinations/ramachandi'
      path: '/ramachandi'
      fullPath: '/destinations/ramachandi'
      preLoaderRoute: typeof DestinationsRamachandiRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/tours/koraput-2-day': {
      id: '/tours/koraput-2-day'
      path: '/koraput-2-day'
      fullPath: '/tours/koraput-2-day'
      preLoaderRoute: typeof ToursKoraput2DayRouteImport
      parentRoute: typeof ToursRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsKoraputRoute: typeof DestinationsKoraputRoute
  DestinationsRamachandiRoute: typeof DestinationsRamachandiRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsKoraputRoute: DestinationsKoraputRoute,
  DestinationsRamachandiRoute: DestinationsRamachandiRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface ToursRouteChildren {
  ToursKoraput2DayRoute: typeof ToursKoraput2DayRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursKoraput2DayRoute: ToursKoraput2DayRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  PlanTripRoute: PlanTripRoute,
  RentACampRoute: RentACampRoute,
  RuralStayRoute: RuralStayRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursRoute: ToursRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
