/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DestinationsKoraputRouteImport } from './routes/destinations.koraput'
import { Route as DestinationsRamachandiRouteImport } from './routes/destinations.ramachandi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsKoraputRoute = DestinationsKoraputRouteImport.update({
  id: '/koraput',
  path: '/koraput',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsRamachandiRoute = DestinationsRamachandiRouteImport.update({
  id: '/ramachandi',
  path: '/ramachandi',
  getParentRoute: () => DestinationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/koraput': typeof DestinationsKoraputRoute
  '/destinations/ramachandi': typeof DestinationsRamachandiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/destinations' | '/destinations/koraput' | '/destinations/ramachandi'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/destinations' | '/destinations/koraput' | '/destinations/ramachandi'
  id:
    | '__root__'
    | '/'
    | '/destinations'
    | '/destinations/koraput'
    | '/destinations/ramachandi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/koraput': {
      id: '/destinations/koraput'
      path: '/koraput'
      fullPath: '/destinations/koraput'
      preLoaderRoute: typeof DestinationsKoraputRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/ramachandi': {
      id: '/destinations/ramachandi'
      path: '/ramachandi'
      fullPath: '/destinations/ramachandi'
      preLoaderRoute: typeof DestinationsRamachandiRouteImport
      parentRoute: typeof DestinationsRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsKoraputRoute: typeof DestinationsKoraputRoute
  DestinationsRamachandiRoute: typeof DestinationsRamachandiRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsKoraputRoute: DestinationsKoraputRoute,
  DestinationsRamachandiRoute: DestinationsRamachandiRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
